apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: test-app
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: test-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-14.2.1
  name: test-app-nginx
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app-nginx
  metrics:
  - type: Pods
    pods:
      metric:
        name: my_custom_metric_nginx_http_requests_total
      target:
        type: AverageValue
        averageValue: 5000m # 5 req/sec
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       averageUtilization: 1000
  #       type: Utilization
